POST http://localhost:3001/api/notes
content-type: application/json

{
"content":"GET and POST are the most important methods of HTTP protocol",
"important":true
}

###

# POST http://localhost:3001/api/notes/4
# content-type: application/json

# {
# "id":4,
# "content":"GET and POST are the most important methods of HTTP protocol",
# "important":true
# }
